apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: sd-p1
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: curl
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: curl
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
